### ISSUE TITLE
Fail downloading problem 472 Guru

### ISSUE THREAD

**Issue by kenrick95** [mamat-rahmat/tlc_backup#1]
[My submission](http://tokilearning.org/submission/49642) (see [screen shot here](https://cloud.githubusercontent.com/assets/3090380/13032470/0702752e-d32f-11e5-9e81-4cfb8f82d3df.png)) for [#472 Guru](http://tokilearning.org/problem/472) did not have a "Download as text" available, and hence the script terminates with the following error message:

```
Traceback (most recent call last):
  File "tlc_backup.py", line 38, in <module>
    content_disposition = response.headers['content-disposition']
  File "C:\Python34\lib\site-packages\requests\structures.py", line 54, in __get
item__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
```

**Comment by mamat-rahmat** [comment]
Thanks @kenrick95, i tried to handle that with [c1de389](https://github.com/mamat-rahmat/tlc_backup/commit/c1de389c858cda8c990b6ff6b607ba98f2f7a864). If there aren't "Downoad as Text" option, i parse the submission page to get source code. 
I've tested it with Windows, but not really sure for the other platform. Would you like to test the newest version with your platform?
Please try if this is working and the source code it get is working too.

**Comment by kenrick95** [comment]
Thanks, now it is working well. Btw, I'm on Windows as well (Windows 10).
