### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by luqmanarifin** [mamat-rahmat/tlc_backup#2]
`python tlc_backup.py [SESSION_ID]`

tidak jalan. Error yang muncul adalah :

```
Traceback (most recent call last):
  File "tlc_backup.py", line 17, in <module>
    for i in range(1, int(last)+1):
ValueError: invalid literal for int() with base 10: '=9'
``
```

**Comment by mamat-rahmat** [comment]
Thanks, fixed with [c6839c8](https://github.com/mamat-rahmat/tlc_backup/commit/c6839c8eda6c754d6fbd1b52fa75ac1fc552c7a3)
